name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Build
        run: |
         npm i -g electroshot
         electroshot google.com 1024 --filename --out effects\ --filename "screenshot.png"
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: effects/screenshot.png
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
